### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by fantostisch** [niinpatel/calendarHTML-Javascript#1]
It looks like you published your code so other people can use and improve it, but right now there is no license that allows anyone to do this. I would like to use this project for a renting calendar for our scouting but without a license we are not legally allowed to do so. Can you please choose a license? A nice website with help is [https://choosealicense.com/](https://choosealicense.com/). If you need help choosing a license please let me know.

**Comment by niinpatel** [comment]
fixed it here https://github.com/niinpatel/calendarHTML-Javascript/commit/303d2433edc6d26ed6cebcf3680820c4cd487b0e

Thanks!
